site_name: Bubblemelon's Win32 API Notes
nav:
- Home: index.md
- My Project Notes:
  - My Paint App : project-notes/paintapp.md
- About: about.md


theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - c++
    - cpp
