site_name: Bubblemelon's Win32 API Notes
nav:
    - Home: 'index.md'
    - About: 'about.md'
    - My Project Notes:
      - 'My Paint App' : 'paintapp.md'
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - c++
    - cpp
